version: '3.8'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d millionaire42"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  spring:
    build:
      context: ./42millionaire_spring
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - spring
    networks:
      - app-network

volumes:
  postgres-data:
    driver_opts:
      type: none
      # device는 마운트할 호스트파일경로임.
      device: ${HOME}/postgres-data
      o: bind

networks:
  app-network:
    driver: bridge
