version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: 42milionaire
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: 42milionaire
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d 42milionaire"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    build: .
    ports:
      - "8080:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/42milionaire
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - spring
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
